services:
  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    volumes:
      - db_service_vol:/var/lib/postgresql/data

volumes:
  db_service_vol: